run-name: GitHub Actions push repository Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: docker build -t myflaskimage .
      - run: docker image ls
      - run: docker tag myflaskimage:latest srichakra769/dockerhub:latest
      - run: docker pull srichakra769/dockerhub:latest
      - run: docker -p 8000:8000 --name myflask_container myflaskimage:latest
